update bin files and add dictionary_list for skk

diff --git a/bin/backup b/bin/backup
--- a/bin/backup
+++ b/bin/backup
@@ -3,21 +3,30 @@
 
 echo "taking a snapshot"
 
-snapshot
+snapshot $1
 
 echo "creating a tar archive file"
 
-backup_dir="/home/hoku/backup"
-snapshot_dir="/home/hoku/backup/snapshot"
-exclude_file="/home/hoku/backup/exclude.txt"
+if [ $1 = '/' ]; then
+	dir_name="root"
+elif [ $1 = '/home' ]; then
+	dir_name="home"
+else
+	echo "invalid argument: first argument must be / or /home"
+	exit 1
+fi
 
-latest_snapshot="$(ls -rt $snapshot_dir | head -n1)"
+backup_dir="/backup"
+snapshot_dir="/snapshots/${dir_name}"
+exclude_file="/backup/exclude.txt"
 
-nice tar cvpf $backup_dir/system_$latest_snapshot.tar.xz \
+latest_snapshot="$(ls -rt ${snapshot_dir} | head -n1)"
+
+nice tar cvpf ${backup_dir}/${dir_name}_${latest_snapshot}.tar.xz \
 	--sparse \
 	--use-compress-prog=pixz \
 	--xattrs \
-	--exclude-from=$exclude_file \
-	-C $snapshot_dir/$latest_snapshot \
+	--exclude-from=${exclude_file} \
+	-C ${snapshot_dir}/${latest_snapshot} \
 	. \
-	> $backup_dir/system_$latest_snapshot.log
+	> ${backup_dir}/${dir_name}_${latest_snapshot}.log
diff --git a/bin/snapshot b/bin/snapshot
--- a/bin/snapshot
+++ b/bin/snapshot
@@ -2,15 +2,24 @@
 # take a snapshot
 
 date=$(date "+%F_%H-%M-%S")
-snapshot_dir="/home/hoku/backup/snapshot"
 
-if [ 10 -le $(ls -1U $snapshot_dir | wc -l) ]; then
-	oldest_snapshot="$(ls -rt $snapshot_dir | tail -n1)"
-	btrfs subvolume delete $snapshot_dir/$oldest_snapshot
+if [ $1 = '/' ]; then
+	snapshot_dir="/snapshots/root"
+elif [ $1 = '/home' ]; then
+	snapshot_dir="/snapshots/home"
+else
+	echo "invalid argument: first argument must be / or /home"
+	exit 1
 fi
 
-if [ -e $snapshot_dir/$date ]; then
+if [ 5 -le $(ls -1U ${snapshot_dir} | wc -l) ]; then
+	oldest_snapshot="$(ls -rt ${snapshot_dir} | tail -n1)"
+	btrfs subvolume delete ${snapshot_dir}/${oldest_snapshot}
+fi
+
+if [ -e ${snapshot_dir}/${date} ]; then
 	echo "snapshot is already exist"
+	exit 1
 else
-	btrfs subvolume snapshot -r / $snapshot_dir/$date
+	btrfs subvolume snapshot -r $1 ${snapshot_dir}/${date}
 fi
